apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-local-ai-ingress
  namespace: demo-local-ai
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: demo-local-ai
                port:
                  number: 8080
            path: /
