apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: {{ .Values.namespace.name }}
data:
  application.properties: |
    spring.application.name={{ .Values.application.name }}
    
    # R2DBC PostgreSQL configuration
    spring.r2dbc.url=r2dbc:postgresql://postgres:{{ .Values.postgres.service.port }}/{{ .Values.postgres.env.POSTGRES_DB }}
    spring.r2dbc.username={{ .Values.postgres.env.POSTGRES_USER }}
    
    # JDBC datasource for Liquibase (still needed for migrations)
    spring.datasource.url=jdbc:postgresql://postgres:{{ .Values.postgres.service.port }}/{{ .Values.postgres.env.POSTGRES_DB }}
    spring.datasource.username={{ .Values.postgres.env.POSTGRES_USER }}
    spring.datasource.driver-class-name=org.postgresql.Driver
    
    # Liquibase configuration
    spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
    spring.liquibase.enabled=true
    
    spring.ai.openai.base-url={{ .Values.config.springAiOpenaiBaseUrl }}
    spring.ai.openai.api-key={{ .Values.config.springAiOpenaiApiKey }}
    spring.ai.openai.chat.model={{ .Values.config.springAiOpenaiChatModel }}
    spring.ai.openai.chat.options.model={{ .Values.config.springAiOpenaiChatOptionsModel }}
    
    # Disable PgVector auto-configuration
    spring.autoconfigure.exclude=org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration
    
    # Swagger/OpenAPI configuration
    springdoc.swagger-ui.path=/swagger-ui.html
    springdoc.api-docs.path=/api-docs
    springdoc.swagger-ui.operationsSorter=alpha
    springdoc.swagger-ui.tagsSorter=alpha
    
    # Stripe API configuration
    stripe.api.publicKey={{ .Values.config.stripeApiPublicKey }}