apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  selector:
    app: {{ .Values.application.name }}
  ports:
  - port: {{ .Values.application.service.port }}
    targetPort: {{ .Values.application.service.targetPort }}
  type: {{ .Values.application.service.type }}