{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterIssuer.name }}
spec:
  acme:
    # Let's Encrypt server URL
    server: {{ .Values.clusterIssuer.server }}
    # Email address used for ACME registration
    email: {{ .Values.clusterIssuer.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ .Values.clusterIssuer.privateKeySecretRef.name }}
    # Enable the HTTP-01 challenge provider
    solvers:
    {{- range .Values.clusterIssuer.solvers }}
    - http01:
        ingress:
          class: {{ .http01.ingress.class }}
          {{- if .http01.ingress.podTemplate }}
          podTemplate:
            spec:
              {{- if .http01.ingress.podTemplate.spec.nodeSelector }}
              nodeSelector:
                {{- range $key, $value := .http01.ingress.podTemplate.spec.nodeSelector }}
                {{ $key }}: {{ $value }}
                {{- end }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}