apiVersion: v2
name: tls
description: A Helm chart for setting up TLS with Let's Encrypt on Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: cert-manager
    version: v1.18.2
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled