apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: demo-local-ai
data:
  application.properties: |
    spring.application.name=demo-local-ai
    
    # R2DBC PostgreSQL configuration
    spring.r2dbc.url=r2dbc:postgresql://postgres:5432/vectordb
    spring.r2dbc.username=postgres
    
    # JDBC datasource for Liquibase (still needed for migrations)
    spring.datasource.url=jdbc:postgresql://postgres:5432/vectordb
    spring.datasource.username=postgres
    spring.datasource.driver-class-name=org.postgresql.Driver
    
    # Liquibase configuration
    spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
    spring.liquibase.enabled=true
    
    spring.ai.openai.base-url=http://airunner:12432/engines
    spring.ai.openai.api-key=not-needed
    spring.ai.openai.chat.model=ai/smollm2
    spring.ai.openai.chat.options.model=ai/smollm2
    
    # Disable PgVector auto-configuration
    spring.autoconfigure.exclude=org.springframework.ai.vectorstore.pgvector.autoconfigure.PgVectorStoreAutoConfiguration
    
    # Swagger/OpenAPI configuration
    springdoc.swagger-ui.path=/swagger-ui.html
    springdoc.api-docs.path=/api-docs
    springdoc.swagger-ui.operationsSorter=alpha
    springdoc.swagger-ui.tagsSorter=alpha
    
    # Stripe API configuration
    stripe.api.publicKey=pk_test_51RsLu2AVptonqAQOut5sBxOroJPgKDOyhgOjpaQ1GYHJktScZxTzzI5u74gGSVSI9tmQElZFIR2LNcITRWKCDSef00aqo55i2K