apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-local-ai
  namespace: demo-local-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-local-ai
  template:
    metadata:
      labels:
        app: demo-local-ai
    spec:
      containers:
      - name: app
        image: moldovean/onion-factory:v0.0.5
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "docker"
        - name: SPRING_R2DBC_URL
          value: "r2dbc:postgresql://postgres:5432/vectordb"
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:postgresql://postgres:5432/vectordb"
        - name: SPRING_AI_OPENAI_BASE_URL
          value: "http://airunner:12432/engines"
        - name: SPRING_R2DBC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SPRING_R2DBC_PASSWORD
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SPRING_DATASOURCE_PASSWORD
        - name: STRIPE_API_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: STRIPE_API_SECRET_KEY
        - name: STRIPE_API_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: STRIPE_API_SECRET_KEY
        volumeMounts:
        - name: app-config
          mountPath: /app/config
        readinessProbe:
          httpGet:
            path: /api-docs
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /api-docs
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 3
      volumes:
      - name: app-config
        configMap:
          name: app-config