# Default values for demo-local-ai Helm chart

# Namespace configuration
namespace:
  create: true
  name: demo-local-ai

# Application configuration
application:
  name: demo-local-ai
  replicas: 1
  image:
    repository: moldovean/onion-factory
    tag: v0.0.7
    pullPolicy: IfNotPresent
  service:
    type: LoadBalancer
    port: 8080
    targetPort: 8080
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi
  probes:
    readiness:
      path: /api-docs
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 3
    liveness:
      path: /api-docs
      initialDelaySeconds: 60
      periodSeconds: 20
      timeoutSeconds: 3

# PostgreSQL configuration
postgres:
  enabled: true
  image:
    repository: ankane/pgvector
    tag: latest
    pullPolicy: IfNotPresent
  service:
    port: 5432
    targetPort: 5432
  persistence:
    enabled: true
    size: 1Gi
    storageClass: default
  env:
    POSTGRES_USER: postgres
    POSTGRES_DB: vectordb
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  probes:
    readiness:
      initialDelaySeconds: 5
      periodSeconds: 5
      timeoutSeconds: 3
    liveness:
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 3

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  host: demo-local-ai.local

# Application configuration
config:
  springProfilesActive: docker
  springAiOpenaiBaseUrl: http://airunner:12432/engines
  springAiOpenaiApiKey: not-needed
  springAiOpenaiChatModel: ai/smollm2
  springAiOpenaiChatOptionsModel: ai/smollm2
  stripeApiPublicKey: pk_test_51RsLu2AVptonqAQOut5sBxOroJPgKDOyhgOjpaQ1GYHJktScZxTzzI5u74gGSVSI9tmQElZFIR2LNcITRWKCDSef00aqo55i2K

# Secrets (should be overridden in a secure way)
secrets:
  springR2dbcPassword: postgres
  springDatasourcePassword: postgres
  stripeApiSecretKey: changeit